# Mail Handle System Configuration

# Server Configuration
server:
  addr: ":8082"

# Database Configuration
database:
  dsn: "root:@tcp(127.0.0.1:3306)/mail_handle?charset=utf8mb4&parseTime=True&loc=Local"

# Gmail API Configuration
gmail:
  credentials_file: "./config/gmail-credentials.json"
  token_file: "token.json"

# Scheduler Configuration
scheduler:
  fetch_interval: "0 */1 * * * *"    # Email fetch interval (every minute)

# Email Processing Configuration
email:
  forward_keywords: ["urgent", "important", "priority"]
  max_retries: 3

# Logging Configuration
log:
  level: "info"
  format: "text"  # text or json 