
server:
  addr: ":8082"

database:
  dsn: "root:@tcp(127.0.0.1:3306)/mail_handle?charset=utf8mb4&parseTime=True&loc=Local"

gmail:
  credentials_file: "./config/gmail-credentials.json"
  token_file: "token.json"

scheduler:
  fetch_interval: "0 */1 * * * *"
  forward_keywords: ["urgent", "important", "priority"]

log:
  level: "info"
  format: "text"  # text or json 